services:
    payment.create:
        class: HOffice\AdminBundle\Lib\Payment\PaymentService
        tags:
            - { name: kernel.event_listener, event: payment.update_trans, method: onPaymentUpdateTrans }  
    balance_month.event:
        class: HOffice\AdminBundle\Lib\Balance\BalanceService
        tags:
            - { name: kernel.event_listener, event: balance_month.create_event, method: onCreateBalanceMonth }  
imports:
    - { resource: addParameters.yml }      
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: HOffice\AdminBundle\Entity\User
    group:
      group_class: Itc\AdminBundle\Entity\Group
