<?php

namespace HOffice\AdminBundle\Entity\Payment;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
}
