<?php

namespace HOffice\AdminBundle\Entity\Reversal;

use Doctrine\ORM\EntityRepository;

/**
 * ReversalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReversalRepository extends EntityRepository
{
}
